import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the end-to-end suite (git-ignored).
    "playwright-report/**",
    "test-results/**",
    // The Expo app has its own toolchain (apps/mobile/eslint.config.js).
    "apps/**",
  ]),
  {
    rules: {
      // A Server Action's signature is fixed by `useActionState`, so an action that needs neither the
      // previous state nor the form data still has to declare both. The leading underscore is how this
      // codebase already says "declared because the shape demands it", and the rule now reads it.
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
    },
  },
]);

export default eslintConfig;
