import 'server-only';
import { z } from 'zod';
import {
  aiAnswerSchema,
  type ApiErrorCode,
  authSessionSchema,
  environmentListSchema,
  ingestAcceptedSchema,
  ingestLogsRequestSchema,
  loginRequestSchema,
  alertSummarySchema,
  deploymentDetailSchema,
  deploymentSummarySchema,
  userPreferencesSchema,
  briefSchema,
  checkupSchema,
  cloudflareOverviewSchema,
  globalSearchResponseSchema,
  incidentDetailSchema,
  incidentSummarySchema,
  errorDetailSchema,
  errorSummarySchema,
  healthSchema,
  meSchema,
  pageSchema,
  problemDetailSchema,
  problemSummarySchema,
  reportSchema,
  repositoryStateSchema,
  serverInfoSchema,
  sessionListSchema,
  sloSummarySchema,
  syntheticSummarySchema,
  systemStatusSchema,
} from '@opswatch/contract';

/**
 * Every route `/api/v1` implements, in one list.
 *
 * It is the single description of the surface: the OpenAPI document is generated from it, and
 * `tests/unit/api-openapi.test.ts` checks it against the route files on disk, so a route cannot exist without being
 * documented and an entry cannot survive its route being deleted.
 */
export type ApiRouteSpec = {
  method: 'get' | 'post' | 'delete';
  /** The path under `/api/v1`, written the way OpenAPI writes it: `/me/sessions/{id}`. */
  path: string;
  /**
   * What each `{name}` in `path` means. The parameters themselves are derived from the template, so one can never
   * be forgotten; this only carries the prose, and a name that is not in the path is a mistake the test catches.
   */
  pathParams?: Record<string, string>;
  operationId: string;
  /**
   * `none` is unauthenticated; `session` needs the browser cookie or a bearer token; `signature` is
   * authenticated by an HMAC over the request, which is how a Lambda in somebody else's AWS account
   * proves who it is when there is nobody to sign in as.
   */
  auth: 'none' | 'session' | 'signature';
  summary: string;
  request?: z.ZodType;
  response?: z.ZodType;
  /** 204 for the routes that answer nothing. */
  status: number;
  /** The failures this route can answer, beyond the ones every route shares. */
  errors: ApiErrorCode[];
};

/** Anything can fail this way, so it is not repeated on every entry. */
export const COMMON_ERRORS: ApiErrorCode[] = ['internal_error'];

const openApiDocumentSchema = z.looseObject({ openapi: z.string(), info: z.object({ title: z.string(), version: z.string() }) });

export const API_ROUTES: ApiRouteSpec[] = [
  {
    method: 'get',
    path: '/server',
    operationId: 'getServerInfo',
    auth: 'none',
    summary: 'Product, version, API version, sign-in methods and feature flags. The only unauthenticated endpoint.',
    response: serverInfoSchema,
    status: 200,
    errors: [],
  },
  {
    method: 'get',
    path: '/openapi.json',
    operationId: 'getOpenApiDocument',
    auth: 'none',
    summary: 'This document, generated from the shared contract schemas.',
    response: openApiDocumentSchema,
    status: 200,
    errors: [],
  },
  {
    method: 'post',
    path: '/ingest/aws/logs',
    operationId: 'ingestAwsLogs',
    auth: 'signature',
    summary:
      'Where an OpsWatch Forwarder delivers CloudWatch log records. Signed with the integration’s own secret, not a session. Queued, never processed inside the request.',
    request: ingestLogsRequestSchema,
    response: ingestAcceptedSchema,
    status: 202,
    errors: ['unauthorized', 'invalid_request', 'rate_limited'],
  },
  {
    method: 'post',
    path: '/auth/login',
    operationId: 'login',
    auth: 'none',
    summary: 'Signs in with a password and mints a bearer token for a non-browser client.',
    request: loginRequestSchema,
    response: authSessionSchema,
    status: 200,
    errors: ['invalid_request', 'invalid_credentials', 'rate_limited', 'forbidden_origin'],
  },
  {
    method: 'post',
    path: '/auth/logout',
    operationId: 'logout',
    auth: 'session',
    summary: 'Revokes the credential the caller presented.',
    status: 204,
    errors: ['unauthorized', 'forbidden_origin'],
  },
  {
    method: 'get',
    path: '/me',
    operationId: 'getMe',
    auth: 'session',
    summary: 'The signed-in user, their role and what they are allowed to do.',
    response: meSchema,
    status: 200,
    errors: ['unauthorized'],
  },
  {
    method: 'get',
    path: '/me/sessions',
    operationId: 'listSessions',
    auth: 'session',
    summary: 'Every session of the caller, so a lost device can be found and cut off.',
    response: sessionListSchema,
    status: 200,
    errors: ['unauthorized'],
  },
  {
    method: 'delete',
    path: '/me/sessions/{id}',
    pathParams: { id: 'The public id of the session to revoke, as `GET /me/sessions` reports it.' },
    operationId: 'revokeSession',
    auth: 'session',
    summary: 'Revokes one session of the caller without rotating the instance secret.',
    status: 204,
    errors: ['unauthorized', 'forbidden_origin', 'not_found'],
  },
  {
    method: 'get',
    path: '/brief',
    operationId: 'getBrief',
    auth: 'session',
    summary: 'What changed in one environment since yesterday, and what to start on.',
    response: briefSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/health',
    operationId: 'getHealth',
    auth: 'session',
    summary: 'Whether one environment is healthy, and what could not be read.',
    response: healthSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/me/preferences',
    operationId: 'getPreferences',
    auth: 'session',
    summary: 'What this user chose for themselves. A user who has set none gets the defaults.',
    response: userPreferencesSchema,
    status: 200,
    errors: ['unauthorized'],
  },
  {
    method: 'post',
    path: '/me/preferences',
    operationId: 'setPreferences',
    auth: 'session',
    summary: 'Updates this user\'s preferences. Partial: only the fields sent are changed.',
    request: userPreferencesSchema,
    response: userPreferencesSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request'],
  },
  {
    method: 'get',
    path: '/alerts',
    operationId: 'listAlerts',
    auth: 'session',
    summary: 'Alerts in one environment, newest first, with how many fires the cooldown suppressed.',
    response: pageSchema(alertSummarySchema),
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'post',
    path: '/ai/ask',
    operationId: 'askOpsWatch',
    auth: 'session',
    summary: 'Asks the configured assistant a question about one environment. The answer is a hypothesis built from evidence OpsWatch already measured, and carries the citations it was built from. `not_found` when no provider is configured.',
    request: z.object({ question: z.string().min(1).max(500) }),
    response: aiAnswerSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found', 'unavailable'],
  },
  {
    method: 'get',
    path: '/deployments',
    operationId: 'listDeployments',
    auth: 'session',
    summary: 'What shipped in one environment, newest first. An empty page means the deployments job has recorded nothing, which is not the same as nothing having shipped.',
    response: pageSchema(deploymentSummarySchema),
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/deployments/{id}',
    pathParams: { id: 'The deployment id, as a list entry reports it.' },
    operationId: 'getDeployment',
    auth: 'session',
    summary: 'One deployment, with the problems that started within half an hour after it. A correlation, never a cause.',
    response: deploymentDetailSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/cloudflare',
    operationId: 'getCloudflareOverview',
    auth: 'session',
    summary: 'What Cloudflare saw at the edge for the zones this instance watches. Every rate is nullable: a zone with no traffic has no cache hit rate.',
    response: cloudflareOverviewSchema,
    status: 200,
    errors: ['unauthorized'],
  },
  {
    method: 'get',
    path: '/search',
    operationId: 'search',
    auth: 'session',
    summary:
      'Finds what OpsWatch holds — problems, errors, alerts, incidents, deployments, repositories, checks, objectives, connections and its own documentation. Live infrastructure is not indexed; a result of kind `sectionSearch` carries the query into the section that can ask AWS for it.',
    response: globalSearchResponseSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/repository',
    operationId: 'getRepositoryState',
    auth: 'session',
    summary: 'Whether a repository provider is connected and verified, and which repositories are recorded. Never carries a token.',
    response: repositoryStateSchema,
    status: 200,
    errors: ['unauthorized'],
  },
  {
    method: 'get',
    path: '/synthetics',
    operationId: 'listSynthetics',
    auth: 'session',
    summary: 'The synthetic checks of one environment and what they saw. A check that has never run reports unknown rather than up.',
    response: pageSchema(syntheticSummarySchema),
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/slos',
    operationId: 'listSlos',
    auth: 'session',
    summary: 'The objectives defined for one environment, measured from stored history. An objective with no history behind it reports no figure rather than a full one.',
    response: pageSchema(sloSummarySchema),
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/incidents',
    operationId: 'listIncidents',
    auth: 'session',
    summary: 'Incidents in one environment, newest first. Bounded: incidents are rare by construction.',
    response: pageSchema(incidentSummarySchema),
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/incidents/{id}',
    pathParams: { id: 'The incident id, as a list entry reports it.' },
    operationId: 'getIncident',
    auth: 'session',
    summary: 'One incident, with its timeline, the problems it links and any notes.',
    response: incidentDetailSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/checkup',
    operationId: 'getCheckup',
    auth: 'session',
    summary: 'What is wrong with how one environment is set up, and how much of the catalogue could run.',
    response: checkupSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/reports',
    operationId: 'getReport',
    auth: 'session',
    summary: 'One period of one section, next to the period before it, from stored rollups only.',
    response: reportSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/errors',
    operationId: 'listErrors',
    auth: 'session',
    summary: 'Error groups in one environment, oldest first on an immutable cursor.',
    response: pageSchema(errorSummarySchema),
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'invalid_cursor', 'not_found'],
  },
  {
    method: 'get',
    path: '/errors/{id}',
    pathParams: { id: 'The error group id, as a list entry reports it.' },
    operationId: 'getError',
    auth: 'session',
    summary: 'One error group and the frames its fingerprint was computed over.',
    response: errorDetailSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/problems',
    operationId: 'listProblems',
    auth: 'session',
    summary: 'Problems in one environment, oldest first on an immutable cursor.',
    response: pageSchema(problemSummarySchema),
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'invalid_cursor', 'not_found'],
  },
  {
    method: 'get',
    path: '/problems/{id}',
    pathParams: { id: 'The problem id, as a list entry reports it.' },
    operationId: 'getProblem',
    auth: 'session',
    summary: 'One problem and the evidence that argued for it.',
    response: problemDetailSchema,
    status: 200,
    errors: ['unauthorized', 'invalid_request', 'not_found'],
  },
  {
    method: 'get',
    path: '/system/status',
    operationId: 'getSystemStatus',
    auth: 'session',
    summary: 'What OpsWatch knows about itself: the collector, its jobs and the database. Admin only.',
    response: systemStatusSchema,
    status: 200,
    errors: ['unauthorized', 'forbidden'],
  },
  {
    method: 'get',
    path: '/environments',
    operationId: 'listEnvironments',
    auth: 'session',
    summary: 'The connection and region pairs every data call is scoped to with ?env=.',
    response: environmentListSchema,
    status: 200,
    errors: ['unauthorized'],
  },
];
